# Generated by Django 4.0 on 2022-02-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drowsiness_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=25)),
                ('NAME', models.CharField(max_length=25)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('TIME', models.DateTimeField(null=True)),
            ],
        ),
    ]
